### ISSUE TITLE
will you add Chinese bio? /  会加入中文简历吗？

### ISSUE THREAD

**Issue by Clayblockunova** [XilinJia/XilinJia.github.io#1]

**Comment by XilinJia** [comment]
What's the purpose? Explain.

**Comment by Clayblockunova** [comment]
I think, you have German and French bio, but no Chinese, it's not so possible for a Chinese to do.
我感觉，你连德语和法语简历都有，就是没有中文，这不太像中国人会做的事情。

**Comment by XilinJia** [comment]
Sorry, my Chinese dropped to kindergarten level, and so I abandoned it long ago.
